#!/bin/bash

set -eu
set -o pipefail
set -o errtrace
trap 'printf "ERROR@%s:%d\n" "${BASH_SOURCE}" "${BASH_LINENO}" 1>&2' ERR

DBUG=0
WRAP=()

### internal debug options

while [[ $# -gt 0 && $1 =~ ^-d ]]
do
  if [[ $DBUG -eq 0 && $1 =~ ^-d[0-9]$ ]]
  then
    let DBUG=arg1=$(sed "s@^-d@@" <<< "$1")
  else
    let DBUG="-1+${#1}"
  fi
  echo "DBUG = $DBUG"
  shift
  [[ $DBUG -gt 2 ]] && WRAP+=("GIT_TRACE=1")
  [[ $DBUG -gt 3 ]] && WRAP+=("GIT_TRACE_PERFORMANCE=1")
  [[ $DBUG -gt 4 ]] && WRAP+=("GIT_TRACE_SETUP=1")
done

### get the root dir of the git repo from the command line arguments

gitroot=.

for arg in "$@"
do
  if [[ -f $arg || -d $arg ]]
  then
    [[ $DBUG -gt 0 ]] && echo "valid path! = $arg"
    gitroot=$arg
    if [[ ! -d $gitroot ]]
    then
      gitroot=$(dirname "$arg")
    fi
    cmd1="git -C $gitroot rev-parse --show-toplevel"
    [[ $DBUG -gt 1 ]] && echo "$cmd1"
    gitroot=$($cmd1)
    break
  fi
done

gitrootR=$(python -c "import os.path; print os.path.relpath('$gitroot', '$(pwd)')")

[[ $DBUG -gt 0 ]] && echo "$gitroot == $gitrootR"

### modify command line arguments

argA=()
for arg in "$@"
do
  if [[ "$gitrootR" == "." ]]
  then
    [[ $DBUG -gt 1 ]] && echo "do nothing as gitrootR == ."
    arg1=$arg
  else
    arg1=$(sed "s@$gitrootR@@" <<< "$arg")
  fi
  arg1=${arg1:-.}
  if [[ "$arg1" =~ ^[/] ]]
  then
    if [[ "$arg1" == "/" ]]
    then
      arg1='.'
    else
      [[ $DBUG -gt 1 ]] && echo "strip / from start"
      arg1=$(sed "s@^/@@" <<< "$arg1")
    fi
  fi
  [[ $DBUG -gt 0 ]] && echo "$arg -> $arg1"
  argA+=($arg1)
done
[[ $DBUG -gt 0 ]] && echo ${#argA[@]}

### execute modified command

cmd=("${WRAP[@]}" git -C "$gitrootR" "${argA[@]}")

[[ $DBUG -gt 1 ]] && echo "argument size = " ${#cmd[@]}
[[ $DBUG -gt 0 ]] && echo "command = ${cmd[*]}"

exec env "${cmd[@]}"
